stickers_codes = [
    "Smile",
    "Grimace",
    "Drool",
    "Scowl",
    "CoolGuy",
    "Sob",
    "Shy",
    "Silent",
    "Sleep",
    "Cry",
    "Awkward",
    "Angry",
    "Tongue",
    "Grin",
    "Surprise",
    "Frown",
    "Blush",
    "Scream",
    "Puke",
    "Chuckle",
    "Joyful",
    "Slight",
    "Smug",
    "Drowsy",
    "Panic",
    "Laugh",
    "Commando",
    "Scold",
    "Shocked",
    "Shhh",
    "Dizzy",
    "Toasted",
    "Skull",
    "Hammer",
    "Bye",
    "Speechless",
    "NosePick",
    "Clap",
    "Trick",
    "Bah！R",
    "Pooh-pooh",
    "Shrunken",
    "TearingUp",
    "Sly",
    "Kiss",
    "Whimper",
    "Happy",
    "Sick",
    "Flushed",
    "Lol",
    "Terror",
    "Let Down",
    "Duh",
    "Hey",
    "Facepalm",
    "Smirk",
    "Smart",
    "Concerned",
    "Yeah!",
    "Onlooker",
    "GoForIt",
    "Sweats",
    "OMG",
    "Emm",
    "Respect",
    "Doge",
    "NoProb",
    "MyBad",
    "Wow",
    "Boring",
    "Awesome",
    "LetMeSee",
    "Sigh",
    "Hurt",
    "Broken",
    "Lips",
    "Heart",
    "BrokenHeart",
    "Hug",
    "ThumbsUp",
    "ThumbsDown",
    "Shake",
    "Peace",
    "Salute",
    "Beckon",
    "Fist",
    "OK",
    "Worship",
    "Beer",
    "Coffee",
    "Cake",
    "Rose",
    "Wilt",
    "Cleaver",
    "Bomb",
    "Poop",
    "Moon",
    "Sun",
    "Party",
    "Gift",
    "Packet",
    "Rich",
    "Blessing",
    "Fireworks",
    "Firecracker",
    "Pig",
    "Waddle",
    "Tremble",
    "Twirl",
]

# print(len(stickers_codes))

markdown_str = """\
||||||||||
|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|
"""

for l in range(14):
    markdown_str += (
        f"|sticker|"
        + "|".join([f"![](./images-stickers/{l*8+i}.png)" for i in range(8 if l != 13 else 5)])
        + "|\n"
    )
    markdown_str += (
        f"|code|" + "|".join([stickers_codes[l * 8 + i] for i in range(8 if l != 13 else 5)]) + "|\n"
    )

print(markdown_str)

# with open("./stickers-codes.md", "w") as f:
#     f.write(markdown_str)
